import { NextResponse } from 'next/server'
import { getSettingByKey } from '@/lib/actions/settings'

export async function POST(req: Request) {
  try {
    const { prompt } = await req.json()
    
    if (!prompt) {
      return NextResponse.json({ error: 'Prompt is required' }, { status: 400 })
    }

    // Get API key from settings or env
    let apiKey = process.env.GEMINI_API_KEY
    try {
      const dbKey = await getSettingByKey('GEMINI_API_KEY')
      if (dbKey) apiKey = dbKey
    } catch (e) {
      console.error("Could not fetch API key from settings", e)
    }

    if (!apiKey) {
      return NextResponse.json({ error: 'Gemini API key not configured' }, { status: 500 })
    }

    // Call Gemini Imagen 3 directly via REST API (using v1alpha as v1beta might not have Imagen enabled for all keys yet)
    const url = `https://generativelanguage.googleapis.com/v1alpha/models/imagen-3.0-generate-001:predict?key=${apiKey}`
    
    try {
      const response = await fetch(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          instances: [
            {
              prompt: prompt
            }
          ],
          parameters: {
            sampleCount: 1,
            aspectRatio: "4:3"
          }
        })
      })

      if (!response.ok) {
        const errText = await response.text()
        console.warn("Gemini Imagen API Error (falling back to Pollinations):", errText)
        throw new Error("Gemini API failed")
      }

      const data = await response.json()
      
      if (!data.predictions || data.predictions.length === 0) {
        throw new Error("No image generated by Gemini")
      }

      const base64Image = data.predictions[0].bytesBase64Encoded
      const mimeType = data.predictions[0].mimeType || 'image/png'
      const dataUrl = `data:${mimeType};base64,${base64Image}`

      return NextResponse.json({ url: dataUrl, source: 'gemini' })
    } catch (apiError) {
      // Fallback: If Gemini fails (key not allowed for Imagen, quota, etc.), use Pollinations but with clean prompt
      const fallbackUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=800&height=600&nologo=true&seed=${Math.floor(Math.random()*10000)}`
      return NextResponse.json({ url: fallbackUrl, source: 'pollinations (fallback)' })
    }

  } catch (error: any) {
    console.error('Error in AI Image Route:', error)
    return NextResponse.json({ error: error.message || 'Internal server error' }, { status: 500 })
  }
}
